Jokes/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "jokes#index"
  post 'jokes/:id/in_like' => 'jokes#in_like', as: 'joke_like'
  post 'jokes/:id/in_dislike' => 'jokes#in_dislike', as: 'joke_dislike'
end

Jokes/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Jokes/app/models/joke.rb
class Joke < ApplicationRecord
end

Jokes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Jokes/app/controllers/jokes_controller.rb
class JokesController < ApplicationController
  def index
    @jokes = Joke.all
    # cookies.signed.permanent[:index] = { value: "XJ-122", expires: 1.hour }
  end

  def in_like
    current_like = Joke.find(params[:id])
    current_like.like +=1
    current_like.save
  end

  def in_dislike
    current_like = Joke.find(params[:id])
    current_like.dislike +=1
    current_like.save
  end

  private

  def set_joke
    @joke = Joke.find(params[:id])
  end

  def joke_params
    params.require(:joke).permit(:content, :like, :dislike)
  end
end

Jokes/app/helpers/application_helper.rb
module ApplicationHelper
end

Jokes/app/helpers/jokes_helper.rb
module JokesHelper
end

Jokes/app/views/footer/_footer.html.erb
<footer>
  <hr>
  <p class="title">This website is created as part of HLsolutions program. The materials contained on this website are
    provided for general information only and do not constitute any form of advice. HLS assumes no responsibility
    for the accuracy of any particular statement and accepts no liability for any loss or damage which may arise
    from reliance on the information contained on this site.
    <br>
    <br>
    <b class ="in_dam">Copyright 2021 HLS</b>
  </p>
</footer>

Jokes/app/views/header/_header.html.erb
<header>
  <%= image_tag "logo", class: "logo"%>
  <div class="user">
    <div class="user_name">
      <p class="han_by">Handicrafted by</p>
      <p class="name">Jim HLS</p>
    </div>
    <%=image_tag "avatar", class: "avatar"%>
  </div>
</header>

Jokes/app/views/jokes/index.html.erb
<section id="main">
  <div class="div_title">
    <h1 class="content_title">A joke a day keeps the docter away</h1>
    <p class="content_title1">if you joke wrong way, your teeth have to pay. (Serious)</p>
  </div>
  <div class="div_content">
    <%@jokes.each do |jok|%>
      <div class="jokes">
        <div class ="content"><%=jok.content%></div>
        <hr>
        <div class="button_vote">
          <%=button_to "This is Funny!", joke_like_path(jok.id), method: :post, class: "voteLike vote", onclick: "plusDivs()"%>
          <%=button_to "This is not funny.", joke_dislike_path(jok.id), method: :post, class: "voteDisLike vote", onclick: "plusDivs()"%>
        </div>
      </div>
    <%end%>
  </div>
</section>

<script>
  var slideIndex = 1;
  showDivs(slideIndex);
  function plusDivs() {
      showDivs((slideIndex += 1));
  }

  function showDivs(n) {
      var i;
      var x = document.getElementsByClassName("jokes");
      if (n > x.length) {
          slideIndex = x.length;
          alert("That's all the jokes for today! Come back another day!");
      }
      for (i = 0; i < x.length; i++) {
          x[i].style.display = "none";
      }
      x[slideIndex - 1].style.display = "block";
  }
</script>

Jokes/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jokes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
  </head>
  <body>
    <div class="container-fluid">
      <%= render 'header/header' %>
      <main>
        <%= yield %>
      </main>
      <%= render 'footer/footer' %>
    </div>
  </body>
</html>